PatternPal/PatternPal

IDesign/IDesign.Extension/Commands/SubscribeBuildEvents.cs, IDesign/IDesign.Extension/IDesign.ExtensionPackage.cs
it now only logs the buildevents when the logging option is set to true (when new things get logged this if statement needs to be added to the eventhandler of that event)
=> #96 has been implemented

IDesign/IDesign.Extension/ViewModels/MainViewModel.cs, IDesign/IDesign.Extension/Views/HomeView.xaml, IDesign/IDesign.Extension/Views/HomeView.xaml.cs
Changed visibility of back button in home view to Collapsed instead of Hidden so it doesn't mess up the xaml flow.
Removed the orientation of the buttons in the home view changing on window size as it doesn't work anymore because of the global scrollviewer
=> Fix logo and logo text not being centered in home view

PatternPal/PatternPal.Extension/ExtensionWindow.cs, PatternPal/PatternPal.Extension/ExtensionWindowPackage.cs, PatternPal/PatternPal.Extension/Grpc/GrpcBackgroundServiceHelper.cs, PatternPal/PatternPal.Extension/PatternPal.Extension.csproj, PatternPal/PatternPal.Extension/PatternPal.ExtensionPackage.cs, PatternPal/PatternPal/Services/PatternPalService.cs
Unfortunately, starting the background service as a child process doesn't result in it being killed along with the parent process, which is why we need to kill it ourselves before VS is closed. This could definitely be improved, and there is still an issue if the code to kill the background service isn't run for some reason. Perhaps we could check whether the background service is already running before starting a new instance.
For now, this seems good enough.
=> Start background service from extension

PatternPal/PatternPal.Extension/Views/DetectorView.xaml, PatternPal/PatternPal.Extension/Views/DetectorView.xaml.cs, PatternPal/PatternPal/Services/RecognizerService.cs, Protos/recognizer.proto
This patch moves the show all functionality to the backend. The only difference with the previous behavior is that the show all button only takes effect on the next analyze call, it doesn't refresh the results.
=> BS+Ext: Fix show all results button

PatternPal/PatternPal.Extension/Views/DetectorView.xaml.cs, PatternPal/PatternPal/Services/RecognizerService.cs, Protos/recognizer.proto
Gets the supported recognizers from the backend. This is done in order to not include the default value of the `Recognizer` enum in the UI.
=> BS+Ext: Get supported recognizers from backend

PatternPal/PatternPal.Core/Checks/ICheck.cs, PatternPal/PatternPal.Core/Checks/ModifierCheck.cs, PatternPal/PatternPal.Core/Checks/NotCheck.cs, PatternPal/PatternPal.Tests/Checks/CheckHelperTests.cs, PatternPal/PatternPal.Tests/Checks/NotCheckTests.cs
The NotCheck returns a NodeCheckResult with a list of ICheckResults as ChildrenCheckResults. This list can either be empty or store one checkResult. 
If the list is empty it means that the at least one childCheck failed and thus the NotCheck succeeded. We do not return the children in that case because it would give a lot of children. 
If the list contains an item the NotCheck failed because all the children were correct. Which lead to a case where the check in the NotCheck existed.
For questions about why I implemented it in this way feel free to contact me!
=> Rec: Implemented NotCheck and coherent Tests and helperMethods

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/patternpal.yml, .github/workflows/test.yml
When skipping the entire sub-workflows, the skipped name differs from when the workflow is run. This makes it impossible to define the checks which are required for merging, because you can't specify both, as they never apply at the same time. To circumvent this issue, I moved the skipping of steps to the sub-workflows, which means the check names are always the same, regardless of whether they're skipped or run.
=> CI: Skip steps individually

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs, PatternPal/PatternPal.Extension/PatternPal.ExtensionPackage.cs, PatternPal/PatternPal.LoggingServer/appsettings.Development.json
Fixed 2 bugs:
1. Grpc Error when multiple projects were opened at the same time and thus multiple requests based on the same request was sent.
2. OnSessionStart called twice at initialization
=> Log: Hotfix for logs Project.Open and Project.Close

PatternPal/PatternPal.Console/PatternPal.ConsoleApp.csproj, PatternPal/PatternPal.Console/Program.cs
Instead of `NDesk.Options`, which is .NET Framework only, we now use [`Spectre.Console`](https://spectreconsole.net/) for command line argument parsing and output.
=> CLI: Remove .NET Framework dependency and use Spectre.Console

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs
Fixed: File.Edit logged regardless whether the user had specified to enable or disable logging.
=> Log: File.Edit only logging when enabled

PatternPal/PatternPal/Services/RecognizerService.cs
Instead of using the values of the `Recognizer` enum (which includes recognizers which we haven't implemented (yet)), get the supported recognizers as determined by the `RecognizerRunner`. This means you only get to select the recognizers which are actually implemented.
=> Rec: Get supported recognizers only

PatternPal/PatternPal.Core/RecognizerRunner.cs, PatternPal/PatternPal.Tests/Core/RecognizerRunnerTests/RecognizerRunnerTests.Incorrect_Relation_Result_Is_Pruned.verified.txt, PatternPal/PatternPal.Tests/Core/RecognizerRunnerTests/RecognizerRunnerTests.cs
The decision whether the parent should be pruned should only be made after its children have been pruned. If we do that check first, and we decide not the prune the parent, we forget to prune its children.
=> Rec: Always prune child results before parent

PatternPal/PatternPal.Tests/BackgroundService/ServiceTests.cs, PatternPal/PatternPal.Tests/Checks/ClassCheckTests.cs, PatternPal/PatternPal.Tests/Checks/ConstructorCheckTests.cs, PatternPal/PatternPal.Tests/Checks/FieldCheckTests.cs, PatternPal/PatternPal.Tests/Checks/InterfaceCheckTests.cs, PatternPal/PatternPal.Tests/Checks/MethodCheckTests.cs, PatternPal/PatternPal.Tests/Checks/ModifierCheckTests.cs, PatternPal/PatternPal.Tests/Checks/NotCheckTests.cs, PatternPal/PatternPal.Tests/Checks/ParameterCheckTests.cs, PatternPal/PatternPal.Tests/Checks/PropertyCheckTests.cs, PatternPal/PatternPal.Tests/Checks/RelationCheckTests.cs, PatternPal/PatternPal.Tests/Core/FileManagerTest.cs, PatternPal/PatternPal.Tests/Core/GenerateSyntaxTreeTest.cs, PatternPal/PatternPal.Tests/Core/RecognizerRunnerTests/RecognizerRunnerTests.cs, PatternPal/PatternPal.Tests/Core/RelationTest.cs, PatternPal/PatternPal.Tests/NodeConverter.cs, PatternPal/PatternPal.Tests/Utils/EntityNodeUtils.cs, PatternPal/PatternPal.Tests/Utils/FileUtils.cs, PatternPal/PatternPal.Tests/Utils/RecognizerContext4Tests.cs, PatternPal/PatternPal.Tests/Utils/RootNode4Tests.cs, PatternPal/PatternPal.Tests/Utils/TestRecognizer.cs
- Removed many unused `using`-directives
- Factored out some `var`'s
- Many tests are totally uncommented; leaving that for now
- I still feel like it is better practice to remove all testcases _at least_ from the building-process of PatternPal; will mark that as a future `TODO`
=> QA: Reviewed PatternPal.Tests

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs
- Included a filter in the `FileWatcher`, excluding all non `.cs`-files. Besides now being centralised rather than handled per event, this also optimises the performance of the watcher itself.
- Fixed accidental `File.Delete`-triggers when files were edited by explicitly checking if the file has actually seized to exists. However, this bug could have been predicted by following the warnings in the `FileWatcher`-documentation.
- Fixed `File.Create`- and `File.Delete`-triggers while building/cleaning a project/solution for`.cs`-files contained in the build artifacts.
=> Log: Fixed FileWatcher-related bugs

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs
Added a check to ensure that the `vsBuildAction` was not cleaning.
=> Log: Fixed compile-log misfire

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs, PatternPal/PatternPal/Services/LoggingService.cs
- Removed redundant private fields in `SubscribeEvents.cs`
- Centralised setting/unsetting the `fileWatcher`
- Prevented setting up the `fileWatcher` when the supplied path was non-existent
=> Log: Optimized FileWatcher-set-up

docs/index.md
I have added usage documentation for the user in the 'Home' page for the GitHub pages. These are the options and use cases for Step-By-Step.
=> Docs: Documentation added for usage of Step-By-Step

docs/dev/stepbystep/guides/implement_an_instructionset.md, docs/dev/toc.yml
I have written the developer documentation for adding design patterns to Step-By-Step. I have written it under the assumption that the 'IChecks' are not in individual methods because the GitHub page for "Implement a Recognizer" also does not do this. 
I have added an additional header that strongly suggests encasing the 'IChecks' in different methods to use them for both the Recognizer and Step-By-Step. This can be found under "Efficiently add to `Recognizer` functionality".
=> Docs: Developer documentation for adding InstructionSet for SBS.

PatternPal/PatternPal.Extension/Commands/NavigateCommand.cs, PatternPal/PatternPal.Extension/ViewModels/StepByStepListViewModel.cs, PatternPal/PatternPal.Extension/Views/StepByStepInstructionsView.xaml.cs
Generally, this improves user-friendliness. The infinite loop that keeps asking the user to provide '.cs' files is gone. It gives a message to the user that the provided file was not valid and simply does not progress the view and viewmodel to the instructions. The user can then try again and select either continue or implement a new design pattern. The same is true for not providing a valid file path for saving.
=> SBS: Allowed the user to abort selecting a file in continue and stopped progressing the viewmodel when no files are provided.

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs, PatternPal/PatternPal/Services/LoggingService.cs
- An unsuccessful lookup in the `_lastCodeState`-dictionary will now lead to a repeated push of the entire codeBase to the server, thus also repopulating the `_lastCodeState` for that specific project.
- Added some whitelines for consistency and improved readability.
=> Log: Implemented dict exception handling

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs, PatternPal/PatternPal.LoggingServer/Migrations/20230619123815_AddOldFileNameColumn.Designer.cs, PatternPal/PatternPal.LoggingServer/Migrations/20230619123815_AddOldFileNameColumn.cs, PatternPal/PatternPal.LoggingServer/Models/ProgSnap2.cs, PatternPal/PatternPal.LoggingServer/Protos/logcollector.proto, PatternPal/PatternPal.LoggingServer/Services/LoggerService.cs, PatternPal/PatternPal/Services/LoggingService.cs, docs/dev/stepbystep/guides/implement_an_instructionset.md, docs/dev/toc.yml
- No codestate is actually generated server-side since we can trace the
renamed file in the database and use that data when restoring the
eventual codestates.
- On a `File.Rename`-event, the respective entry in the local hashed
codestate is deleted and reinserted under the new name.
Currently, the `FileWatcher` does not detect renaming the parent directory of a
`*.cs`-file. Marked that as a bug
for future fix.
@JustNireon; for testing, please reupdate the PostgreSQL-definitions because a new field has been added to the database.
=> Log: Implemented file logging for rename event

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs
The CodeStateSection for `File.Edit` would only include the direct parent directory (unlike other events); that is now fixed.
=> Log: Fixed CodeStateSection for `File.Edit`

PatternPal/PatternPal.LoggingServer/Migrations/20230622094043_ChangeDateTimeoffsetToNormal.Designer.cs, PatternPal/PatternPal.LoggingServer/Migrations/20230622094043_ChangeDateTimeoffsetToNormal.cs, PatternPal/PatternPal.LoggingServer/Models/ProgSnap2.cs, PatternPal/PatternPal.LoggingServer/Services/LoggerService.cs, PatternPal/PatternPal.LoggingServerTests/LoggingTests.cs, PatternPal/PatternPal/Services/LoggingService.cs
- Amended `PatternPal`, `PatternPal.LoggingServer` and `PatternPal.LoggingServerTests`
- `DateTime`s are now stored in `UTC` everywhere; since we are also always querying in that format that should not be too bad since we at least have a specific format to adhere to now. Client should simply be aware of this.
=> Log: Factored out `DateTimeOffset` in favour of `DateTime`

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs, PatternPal/PatternPal/Services/LoggingService.cs
Now also including `ProjectId` for:
- `EvtCompile`
- `EvtCompileError`
- `EvtDebugProgram`
- `EvtXRecognizerRun`
Also caught some bugs in:
- `EvtXRecognizerRun`
- `EvtXStepByStep`
=> Log: Included `ProjectId` as a logged field in extra events

PatternPal/PatternPal.Console/PatternPal.ConsoleApp.csproj
This allows using the following command to create a self-contained (i.e. installing `.NET` is not required) executable:
```sh
dotnet publish --self-contained --configuration Release --output .
```
=> Console: Set single file publish

PatternPal/PatternPal.Extension/ViewModels/StepByStepInstructionsViewModel.cs, PatternPal/PatternPal/Services/StepByStepService.cs
Previously instructions were added either when the current number count was higher or equal to the instruction count up until that point (they are added when requested to the list) or whether the entry at that index was null. This last statement I have been informed by Casper is actually impossible to test with lists because it will return exceptions. So that check never worked in the first place. I have now changed it, but it involves an exception.
=> SBS: Fixed the repeating instruction in the SBS instructions view

PatternPal/PatternPal.Extension/UserControls/ExpanderResults.xaml, PatternPal/PatternPal.Extension/ViewModels/CheckResultViewModel.cs, PatternPal/PatternPal.Extension/ViewModels/PatternResultViewModel.cs, PatternPal/PatternPal.Extension/Views/RecognizerView.xaml.cs, PatternPal/PatternPal/Services/RecognizerService.cs, Protos/common.proto
This fixes the hard-coded progress bar color, and instead makes it dynamic again. The color is based on the percentage of requirements which are correct.
This percentage is also used to determine whether a result should be shown, with the current threshold set to `50%`.
Also determine the feedback message based on the percentage of correct requirements.
=> BS+Ext: Base ProgessBar color on number of correct requirements

PatternPal/PatternPal.Core/Checks/NodeCheck.cs, PatternPal/PatternPal.Core/Checks/RelationCheck.cs, PatternPal/PatternPal.Core/Checks/TypeCheck.cs, PatternPal/PatternPal.Core/Recognizers/DecoratorRecognizer.cs, PatternPal/PatternPal.Core/Runner/RecognizerRunner-ScoreCalculation.cs, PatternPal/PatternPal/Services/RecognizerService.cs
Made several improvements to score calculation:
- No longer use the score of the target of a `Relation/TypeCheck`
- Handle `NodeCheck`s without sub-checks
- Check if `EntityResult` is correct
=> Rec+BS: Improve results scores

PatternPal/PatternPal.Extension/ViewModels/StepByStepListViewModel.cs
Now when the user wants to implement a new pattern a new project is always added to the solution with the name of the design pattern itself. When there is already a design pattern made in the solution of the same name the user is notified.
=> SBS: New project is always added to solution when making new design pattern. 

PatternPal/PatternPal.Extension/ExtensionWindowControl.xaml
Every title in all views now wraps to a max width. Especially noticeable in the SBS adapter instructions view.
=> Ext: Changed title to wrapped text in viewmodels

PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs
Leveraging `dte` to obtain the current `.csproj`-file would sometimes yield an exception; added sanity checks discarding the log request to prevent this.
=> Log: Fixed exception-throwing for `Document.Save`

PatternPal/PatternPal.Core/StepByStep/Resources/Instructions/AdapterInstructions.Designer.cs, PatternPal/PatternPal.Core/StepByStep/Resources/Instructions/AdapterInstructions.resx, PatternPal/PatternPal.Core/StepByStep/Resources/Instructions/BridgeInstructions.Designer.cs, PatternPal/PatternPal.Core/StepByStep/Resources/Instructions/BridgeInstructions.resx, PatternPal/PatternPal/Services/StepByStepService.cs, Protos/step_by_step.proto, docs/dev/recognizers/patterns/adapter.md, docs/dev/recognizers/patterns/bridge.md
Due to some limitations in the score calculation, we unfortunately can't
rely on that to determine if the result is correct. Instead we fallback
to the old way of determining that, which is to run with prune all and
check if any results remain. This does mean that the recognizer
technically runs twice, which is inefficient. However, because a
Step-by-Step implementation is usually quite small, this doesn't really
matter.
=> SBS: Fix determining if step is correct

PatternPal/PatternPal.Extension/Views/RecognizerView.xaml, PatternPal/PatternPal.Extension/Views/RecognizerView.xaml.cs, PatternPal/PatternPal.Extension/Views/StepByStepInstructionsView.xaml.cs
This PR makes the main backend calls (`Recognize` and SBS `Check`) non-blocking, leaving the UI in a responsive state while they are running. There are perhaps a few more cases where we could make calls non-blocking, but they are not worth the effort.
=> Ext: Don't block UI during backend calls

PatternPal/PatternPal.Extension/ViewModels/StepByStepListViewModel.cs
Currently, the file dialog for continue has an initial directory, the last remembered directory. This PR changes it so that it looks for projects in the opened solution. If the name of that project corresponds to the selected design pattern from the drop-down bar it uses that project's folder path as an initial directory. If there is no such project it opens the solution folder path instead that is loaded and if there is neither a project or a solution it has the same behaviour as currently.
=> Feat: SBS continue opens more convenient initial directory in the dialog.

PatternPal/PatternPal.Core/StepByStep/Resources/Instructions/BridgeInstructions.Designer.cs, PatternPal/PatternPal.Core/StepByStep/Resources/Instructions/BridgeInstructions.resx, PatternPal/PatternPal.Core/StepByStep/Resources/Instructions/SingletonInstructions.Designer.cs, PatternPal/PatternPal.Core/StepByStep/Resources/Instructions/SingletonInstructions.resx, PatternPal/PatternPal.Extension/ViewModels/StepByStepListViewModel.cs
The change in the singleton step 1 now informs the user to make a class in which the constructor must be private. 
The changes in the bridge now use 'we' instead of 'I' when referring to bringing it in line with the other design patterns.
Implementing a new pattern but choosing not to add it to the solution now creates a file name with the design pattern instead of 'NewFile'.
=> SBS: changed SBS steps, corrected 'we' use, new file has pattern name
